ethereum:
  rpc_url: "http://127.0.0.1:8545"
  ws_url: "ws://127.0.0.1:8545"
  chain_id: 31337
  contract_address: "0x5fbdb2315678afecb367f032d93f642f64180aa3"
  private_key: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"


database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "admin"
  dbname: "web3_dapp"
security:
  jwt_secret: "your-secret-key"
  encryption_key: "12345678901234567890123456789012"
dev:
  auto_fund_amount: "100"
  faucet_private_key: "0x..."
