version: "3.8"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: web3_dapp
      MYSQL_USER: web3user
      MYSQL_PASSWORD: web3pass
    ports: ["3306:3306"]
    volumes:
      - db_data:/var/lib/mysql



  transactor:
    build: ./services/transactor
    depends_on:
      - mysql
      - geth
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml

  indexer:
    build: ./services/indexer
    depends_on:
      - mysql
      - geth
    ports:
      - "8081:8081"
    volumes:
      - ./config.yaml:/app/config.yaml

volumes:
  db_data:

